import {useMemo,useRef,useState} from 'react';
import readXlsxFile,{readSheet} from 'read-excel-file/browser';
import catalog from './generated/launchpad-catalog.json';
import {buildLaunchRequest,codexRuntimeLauncher,createImportPackage,IMPORT_LIMITS,parseText,profiles,promptExportLauncher,suggestMap,validateLaunchRequest,type CatalogAgent,type ImportPackage,type ProfileId,type Row} from './launchpad-domain';

type Surface='launchpad'|'import'|'skills'|'history';
const agents=catalog.agents as CatalogAgent[];
const download=(name:string,value:unknown,type='application/json')=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
export function App(){
 const [surface,setSurface]=useState<Surface>('launchpad'),[query,setQuery]=useState(''),[category,setCategory]=useState('All');
 const [builder,setBuilder]=useState<CatalogAgent|null>(null),[mode,setMode]=useState(''),[goal,setGoal]=useState(''),[attached,setAttached]=useState<ImportPackage[]>([]),[notice,setNotice]=useState('');
 const [rawRows,setRawRows]=useState<Row[]>([]),[source,setSource]=useState(''),[format,setFormat]=useState(''),[profile,setProfile]=useState<ProfileId>('prospects'),[mapping,setMapping]=useState<Record<string,string>>({}),[confirmed,setConfirmed]=useState(false),[pkg,setPkg]=useState<ImportPackage|null>(null),[paste,setPaste]=useState('');
 const [sheets,setSheets]=useState<string[]>([]),[pendingFile,setPendingFile]=useState<File|null>(null),[selectedSheet,setSelectedSheet]=useState('');
 const [history,setHistory]=useState<{id:string;skill:string;mode:string;prompt:string;created:string}[]>(()=>{try{return JSON.parse(localStorage.getItem('launch-history-v1')||'[]')}catch{return[]}});
 const fileRef=useRef<HTMLInputElement>(null); const allCategories=['All',...new Set(agents.flatMap(a=>a.categories))];
 const filtered=useMemo(()=>agents.filter(a=>(category==='All'||a.categories.includes(category))&&`${a.display_name} ${a.description} ${a.launcher_skill}`.toLowerCase().includes(query.toLowerCase())),[query,category]);
 const launch=builder&&mode&&goal?(()=>{try{return buildLaunchRequest(builder,mode,goal,attached,new Date().toISOString())}catch{return null}})():null;
 const openBuilder=(a:CatalogAgent,imports:ImportPackage[]=[])=>(setBuilder(a),setMode(a.launch_modes[0]),setGoal(''),setAttached(imports),setNotice(''));
 const resetImport=()=>{setRawRows([]);setSource('');setFormat('');setMapping({});setConfirmed(false);setPkg(null);setSheets([]);setPendingFile(null);setSelectedSheet('')};
 const acceptRows=(rows:Row[],name:string,kind:string)=>{if(rows.length>IMPORT_LIMITS.rows)throw new Error(`Maximum ${IMPORT_LIMITS.rows.toLocaleString()} rows.`);setRawRows(rows);setSource(name);setFormat(kind);const headers=Object.keys(rows[0]||{});setMapping(suggestMap(headers,profile));setConfirmed(false);setPkg(null);setNotice(`${rows.length} rows parsed locally. Confirm the profile and mapping.`)};
 const fileChosen=async(file?:File)=>{if(!file)return;resetImport();if(file.size>IMPORT_LIMITS.bytes){setNotice('File rejected: maximum size is 5 MiB.');return}const ext=file.name.split('.').pop()?.toLowerCase();try{if(ext==='xlsx'){const workbook=await readXlsxFile(file);const names=workbook.map(sheet=>sheet.sheet);if(names.length>IMPORT_LIMITS.sheets)throw new Error(`Workbook has more than ${IMPORT_LIMITS.sheets} sheets.`);setSheets(names);setPendingFile(file);setSelectedSheet(names[0]||'');setSource(file.name);setFormat('xlsx');setNotice('Choose a workbook sheet to continue.')}else if(ext==='csv'||ext==='json'||ext==='txt')acceptRows(parseText(await file.text(),ext),file.name,ext);else throw new Error('Choose CSV, XLSX, JSON, or TXT.')}catch(e){setNotice(e instanceof Error?e.message:'The file could not be parsed.')}};
 const loadSheet=async()=>{if(!pendingFile||!selectedSheet)return;try{const matrix=await readSheet(pendingFile,selectedSheet);const [head,...body]=matrix;const headers=(head||[]).map((v,i)=>String(v??`field_${i+1}`));acceptRows(body.map(row=>Object.fromEntries(row.map((v,i)=>[headers[i],v]))),`${pendingFile.name}#${selectedSheet}`,'xlsx')}catch(e){setNotice(e instanceof Error?e.message:'The sheet could not be parsed.')}};
 const confirm=()=>{try{const next=createImportPackage(rawRows,source,format,profile,mapping,new Date().toISOString());setPkg(next);setConfirmed(true);setNotice(`Import complete: ${next.quality_summary.accepted} accepted, ${next.quality_summary.rejected} rejected, ${next.quality_summary.duplicates} duplicates.`)}catch(e){setNotice(e instanceof Error?e.message:'Import validation failed.')}};
 const saveLaunch=()=>{if(!launch)return;const next=[{id:launch.launch_id,skill:launch.launcher_skill,mode:launch.launch_mode,prompt:launch.generated_prompt,created:launch.created_at},...history].slice(0,20);setHistory(next);localStorage.setItem('launch-history-v1',JSON.stringify(next));setNotice('Launch metadata and prompt saved locally. Imported rows were not saved.')};
 return <div className="shell"><a className="skip" href="#content">Skip to content</a><header><button className="brand" onClick={()=>setSurface('launchpad')}><span>AC</span><b>Agent Command Center</b></button><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search agents, skills, outputs…" aria-label="Global search"/></label><div className="local"><i/> Local-only</div></header>
 <aside className="nav" aria-label="Primary navigation"><nav>{([['launchpad','Launchpad','⌂'],['import','Import Expert','⇩'],['skills','Skill Library','◇'],['history','Review / History','◴']] as const).map(([id,label,icon])=><button key={id} className={surface===id?'active':''} onClick={()=>setSurface(id)}><span>{icon}</span>{label}</button>)}</nav><div className="boundary"><strong>Runtime not configured</strong><p>Export a prompt or payload to use in an authenticated Codex session.</p></div></aside>
 <main id="content"><div className="announce" aria-live="polite">{notice}</div>
 {surface==='launchpad'&&<><section className="hero"><div><p className="eyebrow">Seller operating console</p><h1>Choose the next useful workflow.</h1><p>Discover the right tool, prepare trustworthy inputs, and export exactly what Codex needs—without hidden actions.</p></div><button onClick={()=>setSurface('import')}>Import seller data <span>→</span></button></section>
 <section className="start"><div><p className="eyebrow">Start here</p><h2>What are you trying to do?</h2></div><div className="intent-row">{['Prepare a meeting','Prioritize accounts','Draft follow-up','Plan my day'].map(x=><button key={x} onClick={()=>setQuery(x.split(' ').at(-1)||'')}>{x}</button>)}</div></section>
 <section className="recipe"><div className="recipe-number">01</div><div><p className="eyebrow">Recommended sequence</p><h2>{catalog.recipes[0].name}</h2><p>Three inspectable steps · edit before export · external writes blocked</p></div><div className="steps">{catalog.recipes[0].steps.map((s,i)=><span key={s}>{i+1}<b>{catalog.skills.find(k=>k.skill_name===s)?.display_name}</b></span>)}</div><button className="secondary" onClick={()=>openBuilder(agents[6])}>Inspect recipe</button></section>
 <div className="section-head"><div><p className="eyebrow">Registry-backed tools</p><h2>Agents for the work in front of you</h2></div><select value={category} onChange={e=>setCategory(e.target.value)} aria-label="Filter agent category">{allCategories.map(c=><option key={c}>{c}</option>)}</select></div>
 {allCategories.filter(c=>c!=='All').map(group=>{const items=filtered.filter(a=>a.categories.includes(group));return items.length?<section className="agent-group" key={group}><h3>{group}<span>{items.length}</span></h3><div>{items.map((a,i)=><article className={i===0&&group==='Today / Orchestration'?'agent featured':'agent'} key={a.agent_id}><div className="agent-index">{String(agents.indexOf(a)+1).padStart(2,'0')}</div><div className="agent-copy"><div className="badges"><span>{a.approval_gate==='none_read_only'?'Read-only':'Approval before write'}</span><span>{a.required_connectors.length?'Connector optional':'Local inputs'}</span></div><h4>{a.display_name}</h4><p>{a.description}</p><dl><div><dt>Needs</dt><dd>{a.accepted_inputs.slice(0,3).join(', ')}</dd></div><div><dt>Produces</dt><dd>{a.primary_output}</dd></div></dl></div><div className="agent-action"><code>{a.launcher_skill}</code><button onClick={()=>openBuilder(a)}>Prepare launch <span>→</span></button></div></article>)}</div></section>:null})}</>}
 {surface==='import'&&<section className="page"><div className="page-title"><div><p className="eyebrow">Local intake workspace</p><h1>Import Expert</h1><p>Turn messy seller files into a clean, reviewable package. Files never leave this browser.</p></div><div className="limit">5 MiB · 5,000 rows · 10 sheets</div></div><ol className="progress"><li className={rawRows.length?'done':'current'}>1 <span>Add data</span></li><li className={sheets.length?'current':''}>2 <span>Choose source</span></li><li className={rawRows.length&&!confirmed?'current':''}>3 <span>Map & confirm</span></li><li className={confirmed?'done':''}>4 <span>Review & route</span></li></ol>
 {!rawRows.length&&<div className="drop"><div className="drop-icon">⇩</div><h2>Add a local file</h2><p>CSV, XLSX, JSON, or TXT. One file at a time in this release.</p><button onClick={()=>fileRef.current?.click()}>Choose file</button><input ref={fileRef} hidden type="file" accept=".csv,.xlsx,.json,.txt" onChange={e=>void fileChosen(e.target.files?.[0])}/><div className="or">or paste text</div><textarea value={paste} onChange={e=>setPaste(e.target.value)} placeholder={'full_name: Avery Chen\norganization: Northstar Skills Cooperative'} aria-label="Paste structured text"/><button className="secondary" disabled={!paste.trim()} onClick={()=>{try{acceptRows(parseText(paste,'txt'),'pasted-text.txt','txt')}catch(e){setNotice(String(e))}}}>Parse pasted text</button></div>}
 {sheets.length>0&&!rawRows.length&&<div className="mapping"><h2>Choose a workbook sheet</h2><select value={selectedSheet} onChange={e=>setSelectedSheet(e.target.value)}>{sheets.map(s=><option key={s}>{s}</option>)}</select><button onClick={()=>void loadSheet()}>Load selected sheet</button></div>}
 {rawRows.length>0&&!confirmed&&<div className="mapping"><div className="mapping-head"><div><h2>Confirm profile and field mapping</h2><p>{source} · {rawRows.length} source rows · suggestions are not confirmed yet</p></div><label>Import profile<select value={profile} onChange={e=>{const p=e.target.value as ProfileId;setProfile(p);setMapping(suggestMap(Object.keys(rawRows[0]||{}),p))}}>{Object.entries(profiles).map(([id,p])=><option value={id} key={id}>{p.name}</option>)}</select></label></div><table><caption>Suggested field mapping</caption><thead><tr><th>Source header</th><th>Maps to</th><th>Sample type</th></tr></thead><tbody>{Object.keys(rawRows[0]||{}).map(h=><tr key={h}><td>{h}</td><td><select value={mapping[h]||''} onChange={e=>setMapping({...mapping,[h]:e.target.value})}><option value="">Do not import</option>{[...new Set([...profiles[profile].required,...profiles[profile].optional,...Object.values(mapping)])].filter(Boolean).map(f=><option key={f}>{f}</option>)}</select></td><td>{typeof rawRows[0][h]}</td></tr>)}</tbody></table><div className="mapping-actions"><button className="secondary" onClick={resetImport}>Start over</button><button onClick={confirm}>Confirm mapping & validate</button></div></div>}
 {pkg&&<div className="quality"><div className="quality-head"><div><p className="eyebrow">ImportPackage v{pkg.schema_version}</p><h2>Quality review</h2></div><button className="secondary" onClick={()=>download(`${pkg.import_id}.json`,pkg)}>Download JSON</button></div><div className="metrics">{Object.entries(pkg.quality_summary).filter(([k])=>k!=='source_rows').map(([k,v])=><div key={k}><strong>{v}</strong><span>{k}</span></div>)}</div><div className="quality-grid"><section><h3>Accepted preview</h3><pre>{JSON.stringify(pkg.normalized_records.slice(0,2),null,2)}</pre></section><section><h3>Row outcomes</h3>{pkg.rejected_rows.map(r=><p key={r.row}><b>Rejected row {r.row}</b> {r.reasons.join(' ')}</p>)}{pkg.duplicates.map(r=><p key={r.row}><b>Duplicate row {r.row}</b> Canonical row {r.canonical_row} via {r.key}.</p>)}{!pkg.rejected_rows.length&&!pkg.duplicates.length&&<p>No rejected or duplicate rows.</p>}</section></div><h3>Recommended agents</h3><div className="recommendations">{pkg.recommended_launchers.map(id=>{const a=agents.find(x=>x.agent_id===id);return a?<button key={id} onClick={()=>openBuilder(a,[pkg])}><b>{a.display_name}</b><span>Attach package →</span></button>:null})}</div></div>}</section>}
 {surface==='skills'&&<section className="page"><div className="page-title"><div><p className="eyebrow">Authoritative registry</p><h1>Skill Library</h1><p>Every active workflow, with its actual output and approval boundary.</p></div><div className="limit">{catalog.skills.length} active skills</div></div><div className="skill-table" role="region" aria-label="Skill catalog" tabIndex={0}><table><thead><tr><th>Skill</th><th>Category</th><th>Primary output</th><th>Approval</th><th>Action</th></tr></thead><tbody>{catalog.skills.filter(s=>`${s.skill_name} ${s.display_name} ${s.primary_output}`.toLowerCase().includes(query.toLowerCase())).map(s=><tr key={s.skill_name}><td><b>{s.display_name}</b><code>{s.skill_name}</code></td><td>{s.category}</td><td>{s.primary_output}</td><td><span className="pill">{s.approval_gate==='none_read_only'?'Read-only':'Before write'}</span></td><td>{agents.find(a=>a.launcher_skill===s.skill_name)?<button className="link" onClick={()=>openBuilder(agents.find(a=>a.launcher_skill===s.skill_name)!)}>Prepare</button>:<span className="muted">Use in Codex</span>}</td></tr>)}</tbody></table></div></section>}
 {surface==='history'&&<section className="page"><div className="page-title"><div><p className="eyebrow">Opt-in browser storage</p><h1>Review / History</h1><p>Only prompts and launch metadata you explicitly save appear here. Imported rows are never stored.</p></div>{history.length>0&&<button className="secondary danger" onClick={()=>{setHistory([]);localStorage.removeItem('launch-history-v1');setNotice('Local launch history cleared.')}}>Clear local history</button>}</div>{history.length?<div className="history-list">{history.map(h=><article key={h.id}><div><b>{h.skill}</b><code>{h.mode}</code><small>{new Date(h.created).toLocaleString()}</small></div><button className="secondary" onClick={()=>void navigator.clipboard.writeText(h.prompt)}>Copy prompt</button></article>)}</div>:<div className="empty"><span>◴</span><h2>No saved launches</h2><p>Saving is optional. Browser storage is not secure enterprise storage.</p></div>}</section>}
 </main>
 {builder&&<div className="scrim" onMouseDown={e=>{if(e.target===e.currentTarget)setBuilder(null)}}><aside className="builder" role="dialog" aria-modal="true" aria-labelledby="builder-title"><div className="builder-head"><div><p className="eyebrow">Run Builder · export only</p><h2 id="builder-title">{builder.display_name}</h2><code>{builder.launcher_skill}</code></div><button className="icon-button" aria-label="Close Run Builder" onClick={()=>setBuilder(null)}>×</button></div><div className="builder-body"><label>Launch mode<select value={mode} onChange={e=>setMode(e.target.value)}>{builder.launch_modes.map(m=><option key={m}>{m}</option>)}</select></label><label>Your goal<textarea rows={4} value={goal} onChange={e=>setGoal(e.target.value)} placeholder="Describe the specific seller outcome you need…"/></label>{attached.length>0&&<div className="attached"><b>Attached ImportPackage</b><span>{attached[0].import_id} · {attached[0].quality_summary.accepted} accepted records</span></div>}<div className="facts"><div><span>Expected output</span><b>{builder.primary_output}</b></div><div><span>Connector requirements</span><b>{builder.required_connectors.join(', ')||'None required'}</b><small>{builder.connector_fallback}</small></div><div className="warning"><span>Approval boundary</span><b>{builder.approval_gate==='none_read_only'?'Read-only analysis':'Pause before any external write'}</b><small>External writes are impossible in this application.</small></div></div><div className="runtime"><i>○</i><div><b>{codexRuntimeLauncher.capability.label}</b><p>{codexRuntimeLauncher.capability.reason}</p></div></div><label>Codex-ready prompt<textarea className="prompt" rows={14} readOnly value={launch?.generated_prompt||'Complete the goal to generate and validate the prompt.'}/></label></div><div className="builder-foot"><label className="save"><input type="checkbox" onChange={e=>{if(e.target.checked)saveLaunch()}} disabled={!launch}/> Save metadata locally</label><div><button className="secondary" disabled={!launch||!validateLaunchRequest(launch)} onClick={()=>{if(launch)void promptExportLauncher.copy(launch).then(()=>setNotice('Prompt copied.'))}}>Copy prompt</button><button disabled={!launch||!validateLaunchRequest(launch)} onClick={()=>launch&&promptExportLauncher.download(launch)}>Download payload</button></div></div></aside></div>}
 </div>}
