export const IMPORT_LIMITS={bytes:5*1024*1024,rows:5000,sheets:10} as const;
export type ProfileId='prospects'|'accounts'|'opportunities'|'meetings'|'activities'|'generic';
export type Row=Record<string,unknown>;
export type CatalogAgent={agent_id:string;display_name:string;description:string;launcher_skill:string;launch_modes:string[];categories:string[];accepted_inputs:string[];required_connectors:string[];connector_fallback:string;primary_output:string;approval_gate:'none_read_only'|'before_external_write';public_safe:boolean;related_skills:string[]};
export type ImportPackage={schema_version:'1.0';import_id:string;created_at:string;sources:{name:string;format:string;row_count:number}[];profile:ProfileId;confirmed_field_map:Record<string,string>;normalized_records:Row[];rejected_rows:{row:number;reasons:string[]}[];duplicates:{row:number;canonical_row:number;key:string}[];warnings:{row:number;message:string}[];evidence_items:{row:number;source:string}[];unknowns:string[];quality_summary:{source_rows:number;accepted:number;rejected:number;duplicates:number;warnings:number};recommended_launchers:string[];provenance:{step:string;detail:string}[]};
export type LaunchRequest={schema_version:'1.0';launch_id:string;launcher_skill:string;launch_mode:string;related_skills:string[];user_goal:string;input_package_references:string[];connector_requirements:string[];prohibited_actions:string[];approval_gate:string;expected_output:string;generated_prompt:string;created_at:string};

export const profiles:Record<ProfileId,{name:string;required:string[];optional:string[];aliases:Record<string,string[]>;identity:string[];agents:string[]}>= {
 prospects:{name:'Prospects / Contacts',required:['full_name','organization'],optional:['email','title','source_url','observed_at','notes'],aliases:{full_name:['name','contact','prospect'],organization:['company','account','org'],email:['email_address'],title:['job_title'],source_url:['url','source'],observed_at:['date','observed'],notes:['note','provided_note']},identity:['email','full_name+organization'],agents:['prospect-strategy','intent-outreach','pre-call-brief']},
 accounts:{name:'Accounts / Organizations',required:['organization'],optional:['domain','industry','source_url','notes'],aliases:{organization:['account','company','org'],domain:['website','organization_domain'],source_url:['url','source'],notes:['note']},identity:['domain','organization'],agents:['net-new-account','association-trigger','sales-assistant']},
 opportunities:{name:'Opportunities / Pipeline',required:['opportunity','organization'],optional:['stage','amount','close_date','owner','notes'],aliases:{opportunity:['deal','opportunity_name'],organization:['account','company'],amount:['value'],close_date:['close','date'],notes:['note']},identity:['opportunity+organization'],agents:['deal-journey','sales-assistant']},
 meetings:{name:'Meetings / Call Notes',required:['meeting_date'],optional:['organization','attendees','notes','source_url'],aliases:{meeting_date:['date','call_date','start'],organization:['account','company'],attendees:['participants','contacts'],notes:['call_notes','transcript','note'],source_url:['url','source']},identity:['meeting_date+organization'],agents:['pre-call-brief','post-call-debrief']},
 activities:{name:'Activity / Outreach History',required:['activity_date','activity_type'],optional:['organization','contact','channel','notes'],aliases:{activity_date:['date','occurred_at'],activity_type:['type','activity'],organization:['account','company'],contact:['name','prospect'],notes:['note','message']},identity:['activity_date+organization+activity_type'],agents:['daily-todo','intent-outreach']},
 generic:{name:'Generic Structured Data',required:[],optional:[],aliases:{},identity:[],agents:['sales-assistant']}
};
const clean=(v:unknown)=>typeof v==='string'?(v.trim()===''?null:v.trim()):v;
export function suggestMap(headers:string[],profile:ProfileId){const p=profiles[profile],out:Record<string,string>={};for(const h of headers){const n=h.trim().toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');for(const field of [...p.required,...p.optional])if(n===field||p.aliases[field]?.includes(n)){out[h]=field;break}}return out}
function validDate(v:unknown){return v==null||v===''||(!Number.isNaN(Date.parse(String(v))))}
function validUrl(v:unknown,allowBareDomain=false){
 if(v==null||v==='')return true;
 const value=String(v).trim();
 try{
  const url=new URL(allowBareDomain&&!/^[a-z][a-z\d+.-]*:\/\//i.test(value)?`https://${value}`:value);
  return (url.protocol==='http:'||url.protocol==='https:')&&Boolean(url.hostname)&&(!allowBareDomain||!/[\s@]/.test(value));
 }catch{return false}
}
function identity(r:Row,p:ProfileId){for(const rule of profiles[p].identity){const fields=rule.split('+');if(fields.every(f=>r[f]))return `${rule}:${fields.map(f=>String(r[f]).toLowerCase()).join('|')}`}return ''}
export function createImportPackage(rows:Row[],source:string,format:string,profile:ProfileId,map:Record<string,string>,now='2026-07-26T00:00:00.000Z'):ImportPackage{
 if(rows.length>IMPORT_LIMITS.rows)throw new Error(`Row limit exceeded: maximum ${IMPORT_LIMITS.rows}.`);
 const normalized:Row[]=[],rejected:ImportPackage['rejected_rows']=[],duplicates:ImportPackage['duplicates']=[],warnings:ImportPackage['warnings']=[],seen=new Map<string,number>();
 rows.forEach((original,index)=>{const row=index+2,r:Row={_source_row:row};for(const [from,to] of Object.entries(map))if(to)r[to]=clean(original[from]);const missing=profiles[profile].required.filter(f=>!r[f]);const badDate=Object.entries(r).some(([k,v])=>/(^|_)date$|_at$/.test(k)&&!validDate(v));const badEmail=r.email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(r.email));const badUrl=!validUrl(r.source_url)||!validUrl(r.domain,true);const reasons=[...missing.map(f=>`Missing required field: ${f}.`),...(badDate?['Invalid date.']:[]),...(badEmail?['Invalid email.']:[]),...(badUrl?['Invalid URL.']:[])];if(reasons.length){rejected.push({row,reasons});return}const key=identity(r,profile);if(key&&seen.has(key)){duplicates.push({row,canonical_row:seen.get(key)!,key:key.split(':')[0]});return}if(key)seen.set(key,row);for(const field of [...profiles[profile].optional,...profiles[profile].required])if(!(field in r)||r[field]==null)warnings.push({row,message:`${field} is unknown.`});normalized.push(r)});
 const recommended=[...new Set(profiles[profile].agents)];return {schema_version:'1.0',import_id:`import-${hash(`${source}:${rows.length}:${profile}`)}`,created_at:now,sources:[{name:source,format,row_count:rows.length}],profile,confirmed_field_map:map,normalized_records:normalized,rejected_rows:rejected,duplicates,warnings,evidence_items:normalized.map(r=>({row:Number(r._source_row),source})),unknowns:[...new Set(warnings.map(w=>w.message))],quality_summary:{source_rows:rows.length,accepted:normalized.length,rejected:rejected.length,duplicates:duplicates.length,warnings:warnings.length},recommended_launchers:recommended,provenance:[{step:'parse',detail:`Parsed ${format} locally.`},{step:'map',detail:'Applied user-confirmed field mapping.'},{step:'normalize',detail:'Trimmed values and preserved empty fields as unknown.'},{step:'deduplicate',detail:'Kept the earliest valid row for each profile identity key.'}]};
}
export function hash(s:string){let h=2166136261;for(const c of s)h=Math.imul(h^c.charCodeAt(0),16777619);return (h>>>0).toString(36)}
export function parseDelimited(text:string,delimiter=','):Row[]{
 const records:string[][]=[],record:string[]=[],input=text.replace(/^\uFEFF/,'' );let value='',quoted=false;
 for(let i=0;i<input.length;i+=1){const char=input[i];if(char==='"'){if(quoted&&input[i+1]==='"'){value+='"';i+=1}else quoted=!quoted}else if(char===delimiter&&!quoted){record.push(value);value=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&input[i+1]==='\n')i+=1;record.push(value);value='';if(record.some(cell=>cell.trim()))records.push(record.splice(0))}else value+=char}
 if(quoted)throw new Error('Delimited text contains an unclosed quoted value.');record.push(value);if(record.some(cell=>cell.trim()))records.push(record);
 if(!records.length)return[];const headers=records[0].map(header=>header.trim());if(headers.some(header=>!header))throw new Error('Delimited text contains an empty header.');if(new Set(headers.map(header=>header.toLowerCase())).size!==headers.length)throw new Error('Delimited text contains duplicate headers.');
 return records.slice(1).map(values=>Object.fromEntries(values.map((cell,index)=>[headers[index]??`field_${index+1}`,cell])));
}
export function parseText(text:string,format:'csv'|'json'|'txt'):Row[]{if(format==='json'){const value=JSON.parse(text);if(!Array.isArray(value))throw new Error('JSON must contain a top-level array.');if(value.some(row=>row===null||Array.isArray(row)||typeof row!=='object'))throw new Error('Every JSON array item must be an object.');return value as Row[]}if(format==='csv')return parseDelimited(text);const trimmed=text.trim();if(!trimmed)return[];const blocks=trimmed.split(/\n\s*\n/);return blocks.map(block=>Object.fromEntries(block.split(/\n/).map((line,i)=>{const at=line.indexOf(':');return at>0?[line.slice(0,at).trim(),line.slice(at+1).trim()]:[`text_${i+1}`,line]})))}
export function buildLaunchRequest(agent:CatalogAgent,mode:string,goal:string,imports:ImportPackage[]=[],now='2026-07-26T00:00:00.000Z'):LaunchRequest{if(!agent.launch_modes.includes(mode))throw new Error('Choose a valid launch mode.');if(goal.trim().length<8)throw new Error('Describe a goal using at least 8 characters.');const refs=imports.map(p=>p.import_id);const prompt=[`Invoke the exact Codex skill: ${agent.launcher_skill}.`,`Launch mode: ${mode}.`,`User goal: ${goal.trim()}`,`Input artifacts: ${refs.length?refs.join(', '):'No attached ImportPackage; use only context supplied with this prompt.'}`,`Connector requirements: ${agent.required_connectors.length?agent.required_connectors.join(', '):'None required. Do not imply optional connectors are available.'}`,`Connector fallback: ${agent.connector_fallback}`,`Evidence rule: keep supplied evidence, inference, and unknowns visibly separate; do not invent missing values.`,`Approval boundary: ${agent.approval_gate}. Drafting and local preparation are allowed, but do not send messages or write to external systems.`,`Expected deliverable: ${agent.primary_output}.`,`If data is insufficient, return a useful partial deliverable with explicit unknowns and next-input requests.`].join('\n');return {schema_version:'1.0',launch_id:`launch-${hash(`${agent.agent_id}:${mode}:${goal}:${refs.join()}`)}`,launcher_skill:agent.launcher_skill,launch_mode:mode,related_skills:agent.related_skills,user_goal:goal.trim(),input_package_references:refs,connector_requirements:agent.required_connectors,prohibited_actions:['send_email','post_message','update_crm','create_task','modify_calendar'],approval_gate:agent.approval_gate,expected_output:agent.primary_output,generated_prompt:prompt,created_at:now}}
export function validateLaunchRequest(r:LaunchRequest){return r.schema_version==='1.0'&&r.launcher_skill.length>0&&r.user_goal.length>=8&&r.generated_prompt.includes(r.launcher_skill)&&r.prohibited_actions.length>0}
export const promptExportLauncher={capability:{available:true,label:'Copy prompt / Download payload'},copy:async(r:LaunchRequest)=>navigator.clipboard.writeText(r.generated_prompt),download(r:LaunchRequest){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));a.download=`${r.launch_id}.json`;a.click();URL.revokeObjectURL(a.href)}};
export const codexRuntimeLauncher={capability:{available:false,label:'Runtime not configured',reason:'Copy the prompt or download the payload, then open it in an authenticated Codex session.'}};
